# Generated by Django 3.2.6 on 2021-08-04 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('range_start', models.IntegerField()),
                ('range_stop', models.IntegerField()),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='colors.color')),
            ],
        ),
    ]
